{
    "name": "TS Event Management System",
    "summary": "Odoo 16 development",
    "author": "Techsiera",
    "website": "https://www.techsiera.com",
    "category": "Training",
    "version": "16.0.1.0.1",
    "license": "LGPL-3",
    "depends": ["mail"],
    "images":["static/description/banner.jpeg"],
    "data": [
        "security/ir.model.access.csv",
        "data/email_remainder.xml",
        "views/menu.xml",
        "views/event_type_master.xml",
        "views/event_creation_management.xml",
        "views/participant_details.xml",
        "views/sponsor_management.xml",
        "views/speaker_management.xml",
        "views/event_session.xml",
        "views/session_attendance.xml",
    ],
    "demo": [],
}
